### ISSUE TITLE
Automatically deploy the website using github actions

### ISSUE THREAD

**Issue by tompollard** [wfdb/mimic_wfdb_tutorials#20]
We could consider adding the following chunk (or similar) to the GitHub workflow:

```
    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html
``` 

This would rebuild the website whenever we merged a change to the development files.
